//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldGoodAvitoApplication.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int AdID { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public string photo { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual AdStatuses AdStatuses { get; set; }
        public virtual Types Types { get; set; }
        public virtual Users Users { get; set; }
    }
}
